export const SEED_INDUSTRIES = [
  { name: 'Information & Communications Technology', description: 'Software, hardware, networking, cybersecurity, AI and data technologies' },
  { name: 'Finance & Banking', description: 'Banking, insurance, fintech, wealth management and financial services' },
  { name: 'Healthcare & Life Sciences', description: 'Hospitals, clinics, pharmaceuticals, biomedical and healthcare technology' },
  { name: 'Education & Training', description: 'Schools, tertiary institutions, private education and corporate training' },
  { name: 'Engineering & Manufacturing', description: 'Aerospace, precision engineering, electronics and advanced manufacturing' },
  { name: 'Marketing, PR & Communications', description: 'Digital marketing, brand management, public relations and content creation' },
  { name: 'Human Resources & Recruitment', description: 'Talent acquisition, HR management, learning and development' },
  { name: 'Legal & Compliance', description: 'Legal services, compliance, risk management and regulatory affairs' },
  { name: 'Retail & E-commerce', description: 'Retail operations, e-commerce, supply chain and customer experience' },
  { name: 'Logistics & Supply Chain', description: 'Freight, warehousing, supply chain management and last-mile delivery' },
  { name: 'Construction & Built Environment', description: 'Building, civil engineering, architecture and real estate' },
  { name: 'Media & Entertainment', description: 'Broadcasting, digital media, gaming and content production' },
  { name: 'Government & Public Services', description: 'Public administration, policy, social services and smart nation initiatives' },
  { name: 'Hospitality & Tourism', description: 'Hotels, F&B, travel and tourism management' },
  { name: 'Professional Services', description: 'Consulting, accounting, auditing and business advisory' },
];

export const SEED_JOB_ROLES: Record<string, Array<{ name: string; description: string; skill_keywords: string[] }>> = {
  'Information & Communications Technology': [
    { name: 'Software Engineer', description: 'Design, develop and maintain software applications', skill_keywords: ['Python', 'JavaScript', 'Java', 'System Design', 'Git'] },
    { name: 'Senior Software Engineer', description: 'Lead software development teams and architect solutions', skill_keywords: ['System Architecture', 'Microservices', 'Leadership', 'Code Review', 'Cloud'] },
    { name: 'Data Analyst', description: 'Analyse data to derive business insights and recommendations', skill_keywords: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics'] },
    { name: 'Data Scientist', description: 'Build predictive models and AI solutions from data', skill_keywords: ['Machine Learning', 'Python', 'TensorFlow', 'Statistics', 'NLP'] },
    { name: 'Data Engineer', description: 'Build and maintain data pipelines and infrastructure', skill_keywords: ['Spark', 'Kafka', 'SQL', 'Python', 'Cloud Data Platforms'] },
    { name: 'Machine Learning Engineer', description: 'Deploy and optimise ML models in production', skill_keywords: ['MLOps', 'Python', 'TensorFlow', 'Docker', 'Kubernetes'] },
    { name: 'AI Engineer', description: 'Develop AI applications including generative AI and agents', skill_keywords: ['Generative AI', 'LLMs', 'Agentic AI', 'Python', 'Prompt Engineering'] },
    { name: 'Cybersecurity Analyst', description: 'Monitor, detect and respond to security threats', skill_keywords: ['SIEM', 'Threat Intelligence', 'Incident Response', 'Networking', 'CEH'] },
    { name: 'Security Engineer', description: 'Design and implement security architectures and controls', skill_keywords: ['Security Architecture', 'Penetration Testing', 'IAM', 'Cloud Security', 'CISSP'] },
    { name: 'Cloud Architect', description: 'Design and oversee cloud infrastructure and solutions', skill_keywords: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'DevOps'] },
    { name: 'DevOps Engineer', description: 'Build and maintain CI/CD pipelines and automation', skill_keywords: ['Kubernetes', 'Docker', 'Jenkins', 'Terraform', 'Linux'] },
    { name: 'Product Manager', description: 'Define and drive product vision, strategy and roadmap', skill_keywords: ['Product Strategy', 'Agile', 'User Research', 'Data Analytics', 'Stakeholder Management'] },
    { name: 'Technical Project Manager', description: 'Manage delivery of technical projects and programmes', skill_keywords: ['Agile', 'Scrum', 'Risk Management', 'Stakeholder Management', 'PMP'] },
    { name: 'Business Analyst', description: 'Bridge business needs with technology solutions', skill_keywords: ['Requirements Gathering', 'Process Mapping', 'SQL', 'UML', 'Data Analysis'] },
    { name: 'UX/UI Designer', description: 'Design user-centred interfaces and experiences', skill_keywords: ['Figma', 'User Research', 'Prototyping', 'Design Thinking', 'Usability Testing'] },
    { name: 'Network Engineer', description: 'Design and maintain network infrastructure', skill_keywords: ['Cisco', 'Networking', 'CCNA', 'Firewalls', 'VPN'] },
    { name: 'Database Administrator', description: 'Manage and optimise database systems', skill_keywords: ['SQL', 'PostgreSQL', 'Oracle', 'Performance Tuning', 'Backup & Recovery'] },
    { name: 'Programme Manager', description: 'Manage portfolios of related projects and programmes', skill_keywords: ['Programme Management', 'Stakeholder Management', 'Budget Management', 'Governance', 'Change Management'] },
  ],
  'Finance & Banking': [
    { name: 'Financial Analyst', description: 'Analyse financial data and prepare reports', skill_keywords: ['Excel', 'Financial Modelling', 'Bloomberg', 'Accounting', 'Valuation'] },
    { name: 'Risk Manager', description: 'Identify and manage financial and operational risks', skill_keywords: ['Risk Assessment', 'Basel III', 'VaR', 'Credit Risk', 'Compliance'] },
    { name: 'Compliance Officer', description: 'Ensure adherence to regulatory requirements', skill_keywords: ['MAS Regulations', 'AML', 'KYC', 'Compliance Frameworks', 'Risk Management'] },
    { name: 'FinTech Product Manager', description: 'Drive digital banking and payment product development', skill_keywords: ['Digital Payments', 'Open Banking', 'API', 'Product Strategy', 'Agile'] },
    { name: 'Investment Analyst', description: 'Research and analyse investment opportunities', skill_keywords: ['Financial Analysis', 'CFA', 'Portfolio Management', 'Bloomberg', 'Valuation'] },
    { name: 'Relationship Manager', description: 'Manage client relationships and grow portfolio', skill_keywords: ['Client Management', 'Financial Products', 'Sales', 'Communication', 'CRM'] },
    { name: 'Data Analytics Manager', description: 'Lead data analytics initiatives in financial services', skill_keywords: ['Python', 'SQL', 'Machine Learning', 'Risk Analytics', 'Data Governance'] },
  ],
  'Healthcare & Life Sciences': [
    { name: 'Healthcare Administrator', description: 'Manage operations of healthcare facilities', skill_keywords: ['Healthcare Operations', 'Policy', 'Finance', 'HR Management', 'Quality Improvement'] },
    { name: 'Health Informatics Analyst', description: 'Manage and analyse health data systems', skill_keywords: ['HL7', 'EMR Systems', 'SQL', 'Health Data', 'HIPAA'] },
    { name: 'Clinical Research Associate', description: 'Coordinate and monitor clinical trials', skill_keywords: ['GCP', 'ICH Guidelines', 'Protocol Design', 'Data Management', 'Regulatory'] },
    { name: 'Medical Device Sales Manager', description: 'Manage sales of medical devices and equipment', skill_keywords: ['Medical Devices', 'Sales Strategy', 'Clinical Knowledge', 'Account Management', 'MedTech'] },
    { name: 'Biomedical Engineer', description: 'Design and maintain medical equipment and devices', skill_keywords: ['Biomedical Engineering', 'Medical Devices', 'Quality Systems', 'Regulation', 'CAD'] },
  ],
  'Education & Training': [
    { name: 'Instructional Designer', description: 'Design learning programmes and e-learning content', skill_keywords: ['Instructional Design', 'E-learning', 'Articulate', 'ADDIE', 'Learning Analytics'] },
    { name: 'Training Manager', description: 'Manage corporate training and development programmes', skill_keywords: ['Training Needs Analysis', 'Programme Design', 'Facilitation', 'LMS', 'Evaluation'] },
    { name: 'EdTech Product Manager', description: 'Build digital learning products and platforms', skill_keywords: ['EdTech', 'Product Management', 'Learning Design', 'Data Analytics', 'Agile'] },
    { name: 'Corporate Trainer', description: 'Deliver training programmes to working professionals', skill_keywords: ['Facilitation', 'Presentation', 'Adult Learning', 'Content Development', 'Coaching'] },
  ],
  'Engineering & Manufacturing': [
    { name: 'Mechanical Engineer', description: 'Design and develop mechanical systems and products', skill_keywords: ['CAD', 'SolidWorks', 'FEA', 'Manufacturing', 'Project Management'] },
    { name: 'Electrical Engineer', description: 'Design electrical systems and equipment', skill_keywords: ['Circuit Design', 'PLC', 'Electrical Systems', 'AutoCAD', 'Safety Standards'] },
    { name: 'Industrial Engineer', description: 'Optimise manufacturing processes and systems', skill_keywords: ['Lean Manufacturing', 'Six Sigma', 'Process Improvement', 'Statistics', 'Simulation'] },
    { name: 'Manufacturing Manager', description: 'Manage manufacturing operations and production', skill_keywords: ['Production Planning', 'Lean', 'Quality Management', 'Supply Chain', 'Operations'] },
    { name: 'Quality Engineer', description: 'Ensure product and process quality standards', skill_keywords: ['ISO 9001', 'Six Sigma', 'Quality Systems', 'Statistical Analysis', 'Auditing'] },
  ],
  'Marketing, PR & Communications': [
    { name: 'Digital Marketing Manager', description: 'Lead digital marketing campaigns and strategy', skill_keywords: ['SEO/SEM', 'Social Media', 'Content Marketing', 'Analytics', 'Campaign Management'] },
    { name: 'Brand Manager', description: 'Develop and manage brand identity and strategy', skill_keywords: ['Brand Strategy', 'Consumer Insights', 'Creative Development', 'Campaign Management', 'Market Research'] },
    { name: 'Content Strategist', description: 'Plan and execute content marketing strategies', skill_keywords: ['Content Writing', 'SEO', 'Content Calendar', 'Analytics', 'Social Media'] },
    { name: 'PR Manager', description: 'Manage public relations and communications', skill_keywords: ['Media Relations', 'Crisis Communications', 'Copywriting', 'Event Management', 'Social Media'] },
    { name: 'Growth Hacker', description: 'Drive user acquisition and retention through experimentation', skill_keywords: ['A/B Testing', 'Analytics', 'Product Marketing', 'Funnel Optimisation', 'Data Analysis'] },
  ],
  'Human Resources & Recruitment': [
    { name: 'HR Business Partner', description: 'Align HR strategy with business objectives', skill_keywords: ['HR Strategy', 'Change Management', 'Employee Relations', 'Talent Management', 'Analytics'] },
    { name: 'Talent Acquisition Specialist', description: 'Attract and hire top talent for the organisation', skill_keywords: ['Recruiting', 'Employer Branding', 'LinkedIn Recruiting', 'Assessment', 'Candidate Experience'] },
    { name: 'Learning & Development Manager', description: 'Design and manage employee development programmes', skill_keywords: ['L&D Strategy', 'Training Design', 'LMS', 'Coaching', 'Skills Assessment'] },
    { name: 'People Analytics Manager', description: 'Use data to drive HR decisions and insights', skill_keywords: ['HR Analytics', 'Python', 'SQL', 'HRIS', 'Data Visualisation'] },
    { name: 'Compensation & Benefits Manager', description: 'Design and manage total compensation programmes', skill_keywords: ['Job Evaluation', 'Market Benchmarking', 'Benefits Design', 'Payroll', 'Analytics'] },
  ],
  'Logistics & Supply Chain': [
    { name: 'Supply Chain Manager', description: 'Oversee end-to-end supply chain operations', skill_keywords: ['Supply Chain Planning', 'Procurement', 'Logistics', 'ERP', 'Analytics'] },
    { name: 'Logistics Manager', description: 'Manage freight, warehousing and distribution operations', skill_keywords: ['Logistics Operations', 'WMS', 'Route Optimisation', 'KPIs', 'Vendor Management'] },
    { name: 'Procurement Specialist', description: 'Source and procure goods and services', skill_keywords: ['Procurement', 'Contract Management', 'Negotiation', 'Sourcing', 'SAP'] },
    { name: 'Operations Analyst', description: 'Analyse and optimise operational processes', skill_keywords: ['Process Improvement', 'Data Analysis', 'Six Sigma', 'Power BI', 'Lean'] },
  ],
  'Government & Public Services': [
    { name: 'Policy Analyst', description: 'Research and develop public policy recommendations', skill_keywords: ['Policy Research', 'Data Analysis', 'Stakeholder Engagement', 'Report Writing', 'Public Administration'] },
    { name: 'Smart Nation Project Manager', description: 'Lead digital government transformation projects', skill_keywords: ['Digital Government', 'Project Management', 'Agile', 'Stakeholder Management', 'Smart Nation'] },
    { name: 'Public Communications Officer', description: 'Manage government communications and public outreach', skill_keywords: ['Public Communications', 'Social Media', 'Crisis Comms', 'Content Creation', 'Stakeholder Relations'] },
  ],
};
